// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrzMmAzLj0riqgvUDnki0_t8TwQnYa9gg',
    appId: '1:521383375097:web:96574e8e599ac184553228',
    messagingSenderId: '521383375097',
    projectId: 'nifti-mobile-app',
    authDomain: 'nifti-mobile-app.firebaseapp.com',
    storageBucket: 'nifti-mobile-app.appspot.com',
    measurementId: 'G-JSTWW2HN8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuSILDHk3X6YN-dsYWFRiw5BlFI4SX7ps',
    appId: '1:521383375097:android:2af632284add120e553228',
    messagingSenderId: '521383375097',
    projectId: 'nifti-mobile-app',
    storageBucket: 'nifti-mobile-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAucbIQj7efeNlqqrD8LbGlMy2oXGtWvsY',
    appId: '1:521383375097:ios:008c130a4b36456e553228',
    messagingSenderId: '521383375097',
    projectId: 'nifti-mobile-app',
    storageBucket: 'nifti-mobile-app.appspot.com',
    iosClientId: '521383375097-7682pr2ol4a773bicfb78djsbmeb73pc.apps.googleusercontent.com',
    iosBundleId: 'com.testing.niftiLocapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAucbIQj7efeNlqqrD8LbGlMy2oXGtWvsY',
    appId: '1:521383375097:ios:7ec31db2ea5fe86a553228',
    messagingSenderId: '521383375097',
    projectId: 'nifti-mobile-app',
    storageBucket: 'nifti-mobile-app.appspot.com',
    iosClientId: '521383375097-cddmc1goeunk52edl6737nfe7p6ah8au.apps.googleusercontent.com',
    iosBundleId: 'com.example.niftiLocapp.RunnerTests',
  );
}
